import {
  ThemeProvider,
  CounterStoreProvider,
  QueryProvider,
} from '@/providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MainLayout } from '@/Layouts';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>
      <body>
        <CounterStoreProvider>
          <QueryProvider>
            <ThemeProvider defaultTheme="light">
              <MainLayout>{children}</MainLayout>
            </ThemeProvider>
          </QueryProvider>
        </CounterStoreProvider>
      </body>
    </html>
  );
}
